blueprint:
  name: NFC Tag Maintenance Reminder
  description: >
    Track recurring maintenance tasks using NFC tags. Scan a tag when you complete a task, 
    and get reminded after a configurable number of days with snooze support. 
    Examples: HVAC filter replacement, water filter changes, pool filter cleaning, 
    water heater draining, smoke detector battery replacement, car oil changes, 
    gutter cleaning, dryer vent cleaning, etc.
  domain: automation
  input:
    tag_id:
      name: NFC Tag ID
      description: The ID of the NFC tag to scan
      selector:
        text:
    completed_datetime:
      name: Completed Date Helper
      description: input_datetime entity to store when the task was last completed
      selector:
        entity:
          domain: input_datetime
    snoozed_datetime:
      name: Snoozed Date Helper
      description: input_datetime entity to store when the reminder was snoozed
      selector:
        entity:
          domain: input_datetime
    reminder_days:
      name: Days Until Reminder
      description: Number of days before sending a reminder
      default: 90
      selector:
        number:
          min: 1
          max: 1000
          unit_of_measurement: days
    snooze_days:
      name: Snooze Duration
      description: Number of days to snooze the reminder
      default: 3
      selector:
        number:
          min: 1
          max: 30
          unit_of_measurement: days
    reminder_time:
      name: Reminder Time
      description: Time of day to check and send reminders
      default: "10:00:00"
      selector:
        time:
    task_name:
      name: Task Name
      description: Name of the maintenance task (e.g., "HVAC Filter", "Pool Filter", "Water Heater Drain")
      selector:
        text:
    telegram_device_id:
      name: Telegram Device ID (Optional)
      description: Device ID for Telegram notifications. Leave empty to skip Telegram.
      default: ""
      selector:
        text:
    mobile_notify_service:
      name: Mobile Notify Service
      description: Notify service for mobile push (e.g., notify.my_mobile_device)
      selector:
        text:

variables:
  task_name: !input task_name
  completed_datetime: !input completed_datetime
  snoozed_datetime: !input snoozed_datetime
  reminder_days: !input reminder_days
  snooze_days: !input snooze_days
  telegram_device_id: !input telegram_device_id
  snooze_action: "SNOOZE_{{ task_name | upper | replace(' ', '_') }}"

trigger:
  - platform: tag
    tag_id: !input tag_id
    id: tag_scanned
  - platform: time
    at: !input reminder_time
    id: daily_check
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: "{{ snooze_action }}"
    id: snooze_pressed

action:
  - choose:
      # Tag was scanned - log task completion
      - conditions:
          - condition: trigger
            id: tag_scanned
        sequence:
          - service: input_datetime.set_datetime
            target:
              entity_id: !input completed_datetime
            data:
              date: "{{ now().strftime('%Y-%m-%d') }}"
          - action: !input mobile_notify_service
            data:
              message: "{{ task_name }} completed. Next reminder in {{ reminder_days }} days."
          - if:
              - condition: template
                value_template: "{{ telegram_device_id != '' }}"
            then:
              - action: notify.send_message
                target:
                  device_id: "{{ telegram_device_id }}"
                data:
                  message: "{{ task_name }} completed. Next reminder in {{ reminder_days }} days."

      # Daily check - send reminder if due
      - conditions:
          - condition: trigger
            id: daily_check
          - condition: template
            value_template: >
              {{ (now().date() - (states(completed_datetime) | as_datetime).date()).days >= reminder_days }}
          - condition: template
            value_template: >
              {{ (now().date() - (states(snoozed_datetime) | as_datetime | default(as_datetime('2000-01-01'))).date()).days >= snooze_days }}
        sequence:
          - action: !input mobile_notify_service
            data:
              message: "Time to do: {{ task_name }}"
              data:
                actions:
                  - action: "{{ snooze_action }}"
                    title: "Snooze {{ snooze_days }} days"
          - if:
              - condition: template
                value_template: "{{ telegram_device_id != '' }}"
            then:
              - action: notify.send_message
                target:
                  device_id: "{{ telegram_device_id }}"
                data:
                  message: >
                    Time to do: {{ task_name }}! Last completed {{ states(completed_datetime) }}, {{ (now().date() - (states(completed_datetime) | as_datetime).date()).days }} days ago.

      # Snooze button pressed
      - conditions:
          - condition: trigger
            id: snooze_pressed
        sequence:
          - service: input_datetime.set_datetime
            target:
              entity_id: !input snoozed_datetime
            data:
              date: "{{ now().strftime('%Y-%m-%d') }}"
          - action: !input mobile_notify_service
            data:
              message: "{{ task_name }} reminder snoozed for {{ snooze_days }} days."
          - if:
              - condition: template
                value_template: "{{ telegram_device_id != '' }}"
            then:
              - action: notify.send_message
                target:
                  device_id: "{{ telegram_device_id }}"
                data:
                  message: "{{ task_name }} reminder snoozed for {{ snooze_days }} days."